// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NewsList: typeof import('./components/news/news-list.vue')['default']
    NewsListItem: typeof import('./components/news/news-list-item.vue')['default']
    UAlert: typeof import('./components/u-alert.vue')['default']
    UBtn: typeof import('./components/u-btn.vue')['default']
    UHeader: typeof import('./components/u-header.vue')['default']
    UHeading: typeof import('./components/u-heading.vue')['default']
    UInput: typeof import('./components/u-input.vue')['default']
    UTextarea: typeof import('./components/u-textarea.vue')['default']
  }
}

export { }
